### ISSUE TITLE
 Rating screen displaying constantly

### ISSUE THREAD

**Issue by mplusb** [ColorlibHQ/colorlib-login-customizer#116]
Notification “Hey, I noticed you have installed our plugin for 15 day(s) – that’s awesome! Could you please do me a BIG favor and give it a 5-star rating on WordPress? Just to help us spread the word and boost our motivation.”

keeps displaying every few days even though plugin has been rated by us

**Comment by razvanaldea89** [comment]
Think this one is fixed
