### ISSUE TITLE
preview does not work

### ISSUE THREAD

**Issue by mplusb** [ColorlibHQ/colorlib-login-customizer#117]

**Comment by cristianraiber** [comment]
@mplusb - need more details

**Comment by andyluak** [comment]
@mplusb could you give me more details , because the preview in customizer works fine for me .

**Comment by cristianraiber** [comment]
Probably a theme incompatibility, but, since we can't track it down, I'll just go ahead and close this.

**Comment by mplusb** [comment]
on my end, it was actually from this plugin: All In One WP Security
+ Allegiant lite

**Comment by cristianraiber** [comment]
@andyluak - check above comments
