### ISSUE TITLE
Show image only issue on the last template , on the Logo Options tab , the image will not appear

### ISSUE THREAD

**Issue by Florin415** [ColorlibHQ/colorlib-login-customizer#135]
If we choose the last template in the templates tab, go to the logo options after and choose : Show image only, the logo image will not appear : https://prnt.sc/vu9i0f

Tested with WP 5.6

**Comment by TeoAlex** [comment]
When changing to template no.4 the 'logo-settings' option defaults to 'show-text-only' and in this option the 'logo-height' input is not visible and it's default saved value is set to 0. Setting 'logo-settings' to 'show-image-only' shows the logo but with the saved height value ( 0 ) . We should set the default logo-height value for templates no.2 and no.4 to 30 px.
