### ISSUE TITLE
Lost your password field link will not redirect us to the reset password page

### ISSUE THREAD

**Issue by Florin415** [ColorlibHQ/colorlib-login-customizer#138]
The "Lost your password" field will not send us to the reset password page like the "Back to" button , but if we click the middle mouse wheel it will open in a new tab: https://drive.google.com/file/d/1m8GXXrHN01z6gHAEpuwHUYtDUX7tqOzr/view

Tested with WP 5.6

**Comment by TeoAlex** [comment]
Can't replicate the issue. It was most likely either a bug that was fixed or incompatibility with a theme or plugin.
