### ISSUE TITLE
 problem with WordPress 5.9

### ISSUE THREAD

**Issue by mplusb** [ColorlibHQ/colorlib-login-customizer#148]
https://wordpress.org/support/topic/problem-with-wordpress-5-9/

users are having issues with the latest version of WP

**Comment by Rudiberto** [comment]
THX to "spennysimmo" for the workaround to be placed in Custom CSS:

.ml-container #login {
position: absolute;
}

**Comment by TeoAlex** [comment]
Fixed and released
