### ISSUE TITLE
WordPress Customizer create Server 500 Error after saving

### ISSUE THREAD

**Issue by Crypto1101** [ColorlibHQ/colorlib-login-customizer#160]
Hi.

In Wordpress 6.2 Multisite-Setup, i began to change the login form. During editing, the home page got load and i wasnt able to see the customized login form.

To prevent loosing my changes, i saved the customizer.
After that, no more editing on this subsite (via login customizer) is possible:

`caught ReferenceError: VueTrumbowyg is not defined
    at 1 (fake_98c3effb.js:4:15)
    at s (fake_98c3effb.js:1:13)
    at e (fake_98c3effb.js:1:13)
    at fake_98c3effb.js:1:13
customize.php:1     Failed to load resource: the server responded with a status of 500 ()`

Maybe you could help me?

Bye, Enric

**Comment by TeoAlex** [comment]
Could not reproduce this issue. Add more details on how to replicate if this is still happening.
