### ISSUE TITLE
 Deprecated: class-colorlib-login-customizer-css-customization.php line 30

### ISSUE THREAD

**Issue by mplusb** [ColorlibHQ/colorlib-login-customizer#162]
Can you replace the old code please?

Deprecated: Creation of dynamic property Colorlib_Login_Customizer::$base is deprecated in /wp-content/plugins/colorlib-login-customizer/includes/class-colorlib-login-customizer.php on line 98

Deprecated: Creation of dynamic property Colorlib_Login_Customizer::$key_name is deprecated in /wp-content/plugins/colorlib-login-customizer/includes/class-colorlib-login-customizer.php on line 99

Deprecated: Creation of dynamic property Colorlib_Login_Customizer_CSS_Customization::$key_name is deprecated in /wp-content/plugins/colorlib-login-customizer/includes/lib/class-colorlib-login-customizer-css-customization.php on line 30

https://wordpress.org/support/topic/deprecated-class-colorlib-login-customizer-css-customization-php-line-30/

**Comment by a4jp-com** [comment]
Thank you Mihaela.

**Comment by cristianraiber** [comment]
cc @TeoAlex

**Comment by TeoAlex** [comment]
duplicate of this https://github.com/ColorlibHQ/colorlib-login-customizer/issues/169
