### ISSUE TITLE
Change labels 

### ISSUE THREAD

**Issue by cristianraiber** [ColorlibHQ/colorlib-login-customizer#27]
- back to {site_name}
- lost your password

These field types should be a TinyMCE instance so that the user can use a combination of links / regular text here. 

![image](https://user-images.githubusercontent.com/7841556/40908876-b11df116-67f0-11e8-8dec-b9bd65b7df3b.png)

**Comment by cristianraiber** [comment]
@giucu91 - can we find a solution here to change only the labels while keeping the href links?

**Comment by giucu91** [comment]
Fixed in 1.2.4
