### ISSUE TITLE
Custom logos are outputted as HTTP instead of HTTPS

### ISSUE THREAD

**Issue by cristianraiber** [ColorlibHQ/colorlib-login-customizer#37]
More: https://wordpress.org/support/topic/issue-images-in-code-as-http-as-the-whole-site-is-https/

**Comment by giucu91** [comment]
@cristianraiber the custom logo saves the url so if you have website without ssl and then add a ssl certificate you will need to add the logo again

**Comment by cristianraiber** [comment]
@giucu91 - We could recommend users to use this plugin: https://wordpress.org/plugins/really-simple-ssl/
