### ISSUE TITLE
Logo links to w.org instead of the site itself

### ISSUE THREAD

**Issue by puikinsh** [ColorlibHQ/colorlib-login-customizer#40]
From email:

> you provide the colorlib plugin “Custom Login Page Customizer by Colorlib”. After installing and configuration of layout i resumed that clicking on my own logo will not link to my domain but ro wordpress.org. Every other free login costomiser plugin is handling that in a efficient way. nobody wh login in will be redirected by a simple click on the logo.

**Comment by cristianraiber** [comment]
related to: 
#30 
#36

**Comment by giucu91** [comment]
Fixed in 1.2.3
