### ISSUE TITLE
Change 'login' text to something else

### ISSUE THREAD

**Issue by cristianraiber** [ColorlibHQ/colorlib-login-customizer#42]
This should be possible as well through the translation functions, right @giucu91 ? 

https://wordpress.org/support/topic/changing-log-in-button-text/

**Comment by a4jp-com** [comment]
How about the remember me label? I have a Japanese website and wanna change the message there too as well as the login button.

**Comment by cristianraiber** [comment]
@a4jp-com - We'll look into this and update accordingly :)
