### ISSUE TITLE
Logo problems in mobile view

### ISSUE THREAD

**Issue by cristianraiber** [ColorlibHQ/colorlib-login-customizer#43]
https://wordpress.org/support/topic/logo-problems-in-mobile-view/

**Comment by razvanaldea89** [comment]
This seems to be fixed. Can anyone confirm?

**Comment by giucu91** [comment]
We need a max-width 100% for mobile, if we put 500px logo on mobile will be cut.

**Comment by TeoAlex** [comment]
https://github.com/ColorlibHQ/colorlib-login-customizer/assets/19348508/c4ab3a87-4163-46fd-b7c2-413cdd53d13b
