### ISSUE TITLE
plugin\'s CSS is overwriting the theme\'s CSS

### ISSUE THREAD

**Issue by cristianraiber** [ColorlibHQ/colorlib-login-customizer#68]

**Comment by razvanaldea89** [comment]
Can't seem to find any css from the plugin besides the login page / register page / lost password page where it is the scope of this plugin to modify the appearance. Could you give any more info about this problem?

**Comment by cristianraiber** [comment]
@razvanaldea89 - it's actually an issue with the epsilon-toggles inside the Customizer :)

**Comment by razvanaldea89** [comment]
@cristianraiber  it's the old toggle, is that overwriting the theme's css? Also, think we should update to the new toggles.

**Comment by cristianraiber** [comment]
@razvanaldea89 - I second that decision :) I like the new toggles A LOT more than the old ones.
