### ISSUE TITLE
new password and register forms

### ISSUE THREAD

**Issue by mplusb** [ColorlibHQ/colorlib-login-customizer#86]
the same options applied to the login form to be applied to the get a new pass form and add an option to change the Register text color.
https://wordpress.org/support/topic/form-background-color-missing-from-get-new-password-screen/

**Comment by mplusb** [comment]
+1

**Comment by razvanaldea89** [comment]
This seems to be fixed. Register text color, as all links colors, can be changed from Form Button & Links section
